[workspace]
members = ["mdbook-add-copyright", "mdbook-epub-fancy"]
resolver = "2"

[workspace.dependencies]
mdbook = "0.4.37"
pulldown-cmark = "0.9.3"
pulldown-cmark-to-cmark = "11.2.0"
serde_json = "1.0"
toml = "0.8.10"
serde = "1.0.197"
serde_derive = "1.0.197"
semver = "1.0.22"